#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Foreman\kernel;
use Symfony\Component\Console\Application;

$application = new Application();

$kernel = new kernel();
$kernel->registerCommands($application);
$application->run();