#!/usr/bin/env php
<?php

if(file_exists(__DIR__.'/vendor/autoload.php')){
    require __DIR__.'/vendor/autoload.php';
}

if (file_exists(dirname(__FILE__, 3)  .'/autoload.php')){
    require dirname(__FILE__, 3)  .'/autoload.php';
}

use PhpSquad\App\CommandContainer;
use PhpSquad\App\Kernel;
use Symfony\Component\Console\Application;

$application = new Application();
$container = new CommandContainer();
$kernel = new Kernel($container);

$kernel->registerCommands($application);
$application->run();